baseURL = "http://localhost:1313"
buildDrafts = true
buildExpired = true
buildFuture = true
enableMissingTranslationPlaceholders = true

[params]
  env = "development"
  res-minify = false
  res-fingerprint = false
  res-postprocess = false

[minify]
  minifyOutput = false